### ISSUE TITLE
Error when creating scratch org

### ISSUE THREAD

**Issue by DNLZ** [trailheadapps/dreaminvest#1]
I get the following error on the step to create a scratch org

`ERROR running force:org:create:  No such column 'HasSampleData' on sobject of type ScratchOrgInfo.`

Removing [this line](https://github.com/ccoenraets/dreaminvest/blob/860bca755cac4b814bf6eaa7143173ccd0e60601/config/project-scratch-def.json#L4) fixed the issue

**Comment by muenzpraeger** [comment]
Was related to a Spring '18 feature.
